### ISSUE TITLE
Will you release the code ?

### ISSUE THREAD

**Issue by MurrayC7** [sjmoran/neural_curve_layers#1]
Will you release the code? I think your network is so novel! So when will it can be released?

**Comment by sjmoran** [comment]
> Will you release the code? I think your network is so novel! So when will it can be released?

Thank you for your interest in our work! Yes, we intend to release the code soon alongside pre-trained models for the datasets used in the paper.

**Comment by GuideWsp** [comment]
will you release the code in the end of this month?

**Comment by sjmoran** [comment]
> will you release the code in the end of this month?

Hi, thank you for your interest. The code will be released here: https://github.com/huawei-noah. ETA within the next few months. Happy to answer any questions you might have on the research in the meantime.
