### ISSUE TITLE
Codes and trained models for RGB image pairs

### ISSUE THREAD

**Issue by hermosayhl** [sjmoran/neural_curve_layers#3]
### Firstly
All the codes and trained models I modified are located here: [CURL_for_RGB_images](https://wws.lanzous.com/iawOPgk1jmd).
The README.md is really necessary to read.
### Secondly
The dataset I use is avaliable at:  https://pan.baidu.com/s/1_VwqWqpPGw5piLxg8pWEZg    extract code: 0212 
If not convenient, extra link: https://mega.nz/file/IZ9njZBJ#8J-cy5GxWj2NedZu360qU2vkLecXSc9IL_G51_Iymms. 
Factually, the dataset is made from the original Adobe MIT-FiveK datasets and please look up https://data.csail.mit.edu/graphics/fivek/. 

> @inproceedings{fivek,
	author = "Vladimir Bychkovsky and Sylvain Paris and Eric Chan and Fr{\'e}do Durand",
	title = "Learning Photographic Global Tonal Adjustment with a Database of Input / Output Image Pairs",
	booktitle = "The Twenty-Fourth IEEE Conference on Computer Vision and Pattern Recognition",
	year = "2011"
}

**If copyright infringement, please contact me to delete the link.**
### Thirdly
MIT-FiveK datasets; ExpertC; 1-4500 for training and 4501-5000 for testing; Resized to max edge of 512px.
After 30 epoches of training, testing PSNR reaches 25.09db and SSIM reaches 0.9.
Listed below are some results:
![image](https://user-images.githubusercontent.com/49510831/92991539-198dd580-f517-11ea-98d8-09a3fea93ae8.png)

**Comment by sjmoran** [comment]
Thank you hermosayhl!

**Comment by McFly-Jia** [comment]
> Thank you hermosayhl!
Is the data you use in PNG format or JPG format？ Can you release the link of the RGB data you use?
